### ISSUE TITLE
Notification of new session created

### ISSUE THREAD

**Issue by crjohnsonuk** [bonejon/club-session-registration#4]
Until this app, one knew there is a new session by getting a notification from Facebook on the CPRC site.  Assuming that we will not be reproducing every session on Facebook too, then we need an alternative to constantly checking the club session site to see if anyone has added a session.

However, this needs to be switchable in "user settings" only if the user wants it, other wise it could be irritating.

**Comment by bonejon** [comment]
So, for the moment the email service is limited to 200 emails per day, or it has to be paid for. This would send us over the limit really quickly.

For now I've agreed with Nikki that the session leaders need to post on the CPRC page that they have posted a session until people get used to checking the app. I'm starting work on a proper mobile app, but it's going to take a bit of time to get that working. From a native app rather than a web page I'm hopeful I can get in-app notifications working.
